/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/alpha/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/arm/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/arm/include/asm/page-nommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/arm/include/asm/pgtable-nommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/arm/plat-omap/include/plat/iommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/avr32/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/blackfin/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/cris/include/arch-v10/arch/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/cris/include/arch-v32/arch/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/cris/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/frv/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/h8300/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/ia64/include/asm/iommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/ia64/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/m32r/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/m68k/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/m68k/include/asm/sun3mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/microblaze/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/mips/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/mn10300/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/parisc/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/powerpc/include/asm/iommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/powerpc/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/powerpc/include/asm/iseries/iommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/s390/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/score/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/sh/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/sparc/include/asm/iommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/sparc/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/sparc/include/asm/pgtsrmmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/um/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/um/include/shared/um_mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/x86/include/asm/amd_iommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/x86/include/asm/iommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/x86/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/x86/kvm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/x86/xen/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/xtensa/include/asm/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/arch/xtensa/include/asm/nommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/drivers/mxc/amd-gpu/include/gsl_mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/include/asm-generic/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/include/config/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/include/config/cpu/cp15/mmu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/include/linux/intel-iommu.h
/home/ricardo/LTIB/ltib/rpm/BUILD/linux-2.6.35.3/include/linux/iommu.h
/home/ricardo/imx_git/imx53_u-boot/include/asm-arm/mmu.h
/home/ricardo/imx_git/imx53_u-boot/include/asm-arm/arch-mx35/mmu.h
/home/ricardo/imx_git/imx53_u-boot/include/asm-arm/arch-mx50/mmu.h
/home/ricardo/imx_git/imx53_u-boot/include/asm-arm/arch-mx51/mmu.h
/home/ricardo/imx_git/imx53_u-boot/include/asm-arm/arch-mx53/mmu.h
/home/ricardo/imx_git/imx53_u-boot/include/asm-arm/arch-mx6/mmu.h
/home/ricardo/imx_git/imx53_u-boot/include/asm-ppc/mmu.h
/home/ricardo/imx_git/imx53_u-boot/include/asm-sparc/srmmu.h
/usr/src/linux-headers-3.2.0-23/arch/alpha/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/arm/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/arm/include/asm/page-nommu.h
/usr/src/linux-headers-3.2.0-23/arch/arm/include/asm/pgtable-nommu.h
/usr/src/linux-headers-3.2.0-23/arch/arm/mach-exynos/include/mach/regs-sysmmu.h
/usr/src/linux-headers-3.2.0-23/arch/arm/mach-exynos/include/mach/sysmmu.h
/usr/src/linux-headers-3.2.0-23/arch/arm/mach-msm/include/mach/iommu.h
/usr/src/linux-headers-3.2.0-23/arch/arm/plat-omap/include/plat/iommu.h
/usr/src/linux-headers-3.2.0-23/arch/arm/plat-samsung/include/plat/sysmmu.h
/usr/src/linux-headers-3.2.0-23/arch/avr32/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/blackfin/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/cris/include/arch-v10/arch/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/cris/include/arch-v32/arch/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/cris/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/frv/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/h8300/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/hexagon/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/hexagon/include/asm/vm_mmu.h
/usr/src/linux-headers-3.2.0-23/arch/ia64/include/asm/iommu.h
/usr/src/linux-headers-3.2.0-23/arch/ia64/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/m32r/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/m68k/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/m68k/include/asm/sun3mmu.h
/usr/src/linux-headers-3.2.0-23/arch/microblaze/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/mips/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/mn10300/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/openrisc/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/parisc/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/powerpc/include/asm/iommu.h
/usr/src/linux-headers-3.2.0-23/arch/powerpc/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/powerpc/include/asm/iseries/iommu.h
/usr/src/linux-headers-3.2.0-23/arch/s390/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/score/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/sh/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/sparc/include/asm/iommu.h
/usr/src/linux-headers-3.2.0-23/arch/sparc/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/sparc/include/asm/pgtsrmmu.h
/usr/src/linux-headers-3.2.0-23/arch/tile/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/um/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/unicore32/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/x86/include/asm/iommu.h
/usr/src/linux-headers-3.2.0-23/arch/x86/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/xtensa/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-23/arch/xtensa/include/asm/nommu.h
/usr/src/linux-headers-3.2.0-23/include/asm-generic/mmu.h
/usr/src/linux-headers-3.2.0-23/include/linux/amd-iommu.h
/usr/src/linux-headers-3.2.0-23/include/linux/intel-iommu.h
/usr/src/linux-headers-3.2.0-23/include/linux/iommu.h
/usr/src/linux-headers-3.2.0-23-generic/include/config/mmu.h
/usr/src/linux-headers-3.2.0-23-generic/include/config/amd/iommu.h
/usr/src/linux-headers-3.2.0-23-generic/include/config/calgary/iommu.h
/usr/src/linux-headers-3.2.0-23-generic/include/config/gart/iommu.h
/usr/src/linux-headers-3.2.0-23-generic/include/config/intel/iommu.h
/usr/src/linux-headers-3.2.0-23-generic/include/linux/amd-iommu.h
/usr/src/linux-headers-3.2.0-23-generic/include/linux/intel-iommu.h
/usr/src/linux-headers-3.2.0-23-generic/include/linux/iommu.h
/usr/src/linux-headers-3.2.0-24/arch/alpha/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-24/arch/arm/include/asm/mmu.h
/usr/src/linux-headers-3.2.0-24/arch/arm/include/asm/page-nommu.h
/usr/src/linux-headers-3.2.0-24/arch/arm/include/asm/pgtable-nommu.h
/usr/src/linux-headers-3.2.0-24/arch/arm/mach-exynos/include/mach/regs-sysmmu.h
/usr/src/linux-headers-3.2.0-24/arch/arm/mach-exynos/include/mach/sysmmu.h
/usr/src/linux-headers-3.2.0-24/arch/arm/mach-msm/include/mach/iommu.h
/usr/src/linux-headers-3.2.0-24/arch/arm/plat-omap/include/pl